# Generated by Django 3.2 on 2022-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5_ecommerce_store', '0002_alter_product_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ID',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
