# Generated by Django 3.2 on 2022-04-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5_ecommerce_store', '0004_auto_20220330_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='state',
            field=models.CharField(choices=[('open', 'open'), ('checkout', 'checked_out'), ('closed', 'closed')], default='open', max_length=15),
        ),
    ]
