# Generated by Django 3.2 on 2022-04-02 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p5_ecommerce_store', '0005_bag_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bagitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
