# Generated by Django 3.2 on 2022-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5_ecommerce_store', '0006_auto_20220402_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
