# Generated by Django 3.2 on 2022-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5_ecommerce_store', '0010_auto_20220424_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
